services:
  api:
    build:
      context: .
      dockerfile: api/api.Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - red

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - red

  nodo1:
    build:
      context: .
      dockerfile: Nodos/Node1/Dockerfile
    container_name: nodo1
    networks:
      - red

  nodo2:
    build:
      context: .
      dockerfile: Nodos/Node2/Dockerfile
    container_name: nodo2
    networks:
      - red

  nodo3:
    build:
      context: .
      dockerfile: Nodos/Node3/Dockerfile
    container_name: nodo3
    networks:
      - red

networks:
  red:
    driver: bridge
